### PR TITLE
Handle duplicate entries in certain fields for add or edit command

### LINKED ISSUE #82: Handle duplicate entries in certain fields for add and edit commands
Policy number should only be used once, with the exception of default value

Entries in the database of different names should be possible when they diverge in different parameters eg. same name but different IC. 

So the following must be called as exceptions
1. Adding or editing a policy number that exists
2. Adding or editing a person with one similar attribute should be fine

### PR DESCRIPTION
**Pull request by RSXIX**
All persons must now have distinct policy numbers. It will not allow the addition or editing of a person with a policy number in use. This does not apply for those without a policy specified.

Persons with the same name can also now be added. A person will only be considered a duplicate if ALL FIELDS are the same.

An exception is thrown for duplicate person and then for duplicate policy number.

Closes #82

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -62,6 +63,10 @@ public CommandResult execute(Model model) throws CommandException {
             throw new CommandException(MESSAGE_DUPLICATE_PERSON);
         }
 
+        if (model.hasPolicyNumber(toAdd)) {
+            throw new CommandException(MESSAGE_USED_POLICY_NUMBER);
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/commands/AddCommand.java]: Nice that you used the `throw` keyword rather than the usual `return` when handling exceptions that doesn't use `try`

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 2]
```diff
@@ -97,10 +98,30 @@ public CommandResult execute(Model model) throws CommandException {
...
+        System.out.println(editedPerson);
+
+        System.out.println("isSamePerson");
+        System.out.println(personToEdit.isSamePerson(editedPerson));
+        System.out.println("hasPerson");
+        System.out.println(model.hasPerson(editedPerson));
+        System.out.println("Compare Policy Number");
+        System.out.println(editedPerson.comparePolicyNumber(personToEdit));
+        System.out.println("Has Policy Number");
+        System.out.println(model.hasPolicyNumber(editedPerson));
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: I am not sure what these lines are for as we do not use the standard I/O library in our code

File: src/main/java/seedu/address/model/AddressBook.java [hunk 3]
```diff
@@ -67,6 +67,14 @@ public boolean hasPerson(Person person) {
         return persons.contains(person);
     }
 
+    /**
+     * Returns true if a person with the same policy number as {@code person} in the address book.
+     */
+    public boolean hasPolicyNumber(Person person) {
```
Comment (brendanneojw) [inline src/main/java/seedu/address/model/AddressBook.java]: I think the naming of this function can be more clear like `hasSamePolicyNumber` because `hasPolicyNumber` sounds like it is checking if the policy number exist.

```suggestion
    public boolean hasSamePolicyNumber(Person person) {
```

**Review by brendanneojw — CHANGES_REQUESTED** [review]
Just require a few changes for code quality purposes.

**Review by brendanneojw — APPROVED** [review]
LGTM!
