### PR TITLE
Fix a bug in the find command for policy expiry and issue dates

### LINKED ISSUE #76: Bug in Find command shows persons with default policy dates
Due to our implementation of the default policy expiry dates and policy issue dates, if the user were to type `find pi/01-01` or `find pe/01-01` , it will list those persons who don't have any policy yet as the default date given for those persons without policies is `01-01-1000`.

### PR DESCRIPTION
**Pull request by brendanneojw**
Closes #76

Now when user uses the command with either `find pi/01-01` or `find pe/01-01` , it will not display the persons with the default policy date of `01-01-1000`.

### CODE REVIEW

File: src/main/java/seedu/address/model/person/PolicyExpiryContainsKeywordsPredicate.java [hunk 1]
```diff
@@ -13,8 +14,8 @@ public PolicyExpiryContainsKeywordsPredicate(String keyword) {
 
     @Override
     public boolean test(Person person) {
-        return keywords.stream()
-                .anyMatch(keyword -> StringUtil.containsWordIgnoreCase(
+        return !person.getPolicy().getPolicyExpiryDate().toString().equals(PolicyDate.DEFAULT_VALUE)
```
Comment (KumChaiYin) [inline src/main/java/seedu/address/model/person/PolicyExpiryContainsKeywordsPredicate.java:17]: Great in using the PolicyDate.DEFAULT_VALUE (instead of hardcoded date)

**Review by KumChaiYin — APPROVED** [review]
LGTM
The changes is intuitive to understand.
Solve the bugs mentioned.
