### PR TITLE
Fix bugs from PED

### LINKED ISSUE #172: [PE-D][Tester A] Contact number should only allow 8 digit numbers
As mentioned in the user guide, the phone number should only allow exactly 8 digits. But the programme allows 3 digit.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: AaronJT1/ped#7

### LINKED ISSUE #174: [PE-D][Tester C] `remark` allows for multiple `remark`s to be saved, but overwrites the first remark.
Running `remark 1 r/This is a test remark. r/This is the second remark` results in only the second remark being saved, only showing the remark "This is the second remark".

I think this is because your regex/logic breaks the string up using "r/", and then only saves the last group? Consider specifying this overwriting behaviour in the UG? I think can just try splitting by spaces instead: i.e. take everything in the second space onwards as the note. Or actually even better to restrict input to alphanumeric + punctuation for actual PE.

So new format would be 
`remark 1 This is a note and whatever is left of the second space is a note` resulting in a remark "This is a note and whatever is left of the second space is a note".

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: conradsoon/ped#12

### LINKED ISSUE #175: [PE-D][Tester C] `remark` command allows for any characters, but presence of "r/" in string causes buggy behaviour.
In UG, `remark` command is specified as allowing any character.

```
Acceptable values for each parameter:

INDEX : It must be a must be a positive integer 1, 2, 3, …​
REMARK : Any characters
```

Suppose I want to save the string "This is a test remark. By the way, my favourite characters are r/." as a remark.

Running the command `remark 1 r/This is a test remark. By the way, my favourite characters are r/.`
saves the remark as `.` instead.

I think this is because your regex/logic breaks the string up using "r/", and then only saves the last group? I think can just try splitting by spaces instead: i.e. take everything in the second space onwards as the note. Or actually even better to restrict input to alphanumeric + punctuation for actual PE.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: conradsoon/ped#13

### LINKED ISSUE #179: [PE-D][Tester D] App doesn't respond to commands with invalid dates
app doesn't respond to command with invalid date 19-15-2024 and doesn't show any error

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: iantsaii/ped#7

### LINKED ISSUE #182: [PE-D][Tester D] App doesn't show warning for invalid dates in February
The command result quietly changes the date from 31-02-2024 to 29-02-2024 even though that might not have been what the user wanted

**Command:** 

**Command Result:**

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: iantsaii/ped#8

### LINKED ISSUE #183: [PE-D][Tester C] Non-standard names not supported by app
I have clients called `RAJU S/O DINESHWAR` and I would like to save his name as such:
`add n/Raju S/O Dineshwar p/222 e/raju@test i/888Z l/SKK1000A a/Test`

However, this is not allowed by the app, which only allows alphanumeric names. Not supporting non-standard names might result in less functionality for users with clients with non-standard names.

I think would be good to implement this feature (or actually better to write this as a "Planned Enhancement" for actual PE).

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: conradsoon/ped#14

### LINKED ISSUE #198: Find command should not take preamble
`find a n/b` should not be a valid command due to the presence of a preamble, but it is still accepted in the app

### PR DESCRIPTION
**Pull request by cyaoxuan**
- Verify that there is no preamble for find command (closes #198)
- Handle duplicate `r/` fields in remark command to fix unintended behaviour when "r/" found in the remarks (closes #174, closes #175)
- Update checks to ensure that invalid dates are caught and made known to the user (closes #179, closes #182)
- Update checks to ensure that phone numbers are exactly 8 digits long (closes #172)

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java [hunk 1]
```diff
@@ -37,19 +38,15 @@ public class FindCommandParser implements Parser<FindCommand> {
...
-        }
-
         ArgumentMultimap argMultimap =
                 ArgumentTokenizer.tokenize(args, PREFIX_NAME, PREFIX_PHONE, PREFIX_EMAIL, PREFIX_TAG,
                         PREFIX_NRIC, PREFIX_LICENCE_PLATE, PREFIX_COMPANY,
                         PREFIX_POLICY_NUMBER, PREFIX_POLICY_ISSUE_DATE,
                         PREFIX_POLICY_EXPIRY_DATE);
 
+        if (!argMultimap.getPreamble().isEmpty()) {
+            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, MESSAGE_PREAMBLE_DETECTED));
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/parser/FindCommandParser.java:48]: Nice to check if there is a preamble before the prefixes

File: src/main/java/seedu/address/logic/parser/RemarkCommandParser.java [hunk 2]
```diff
@@ -32,6 +32,7 @@ public RemarkCommand parse(String args) throws ParseException {
                     RemarkCommand.MESSAGE_USAGE), ive);
         }
 
+        argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_REMARK);
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/parser/RemarkCommandParser.java:35]: Nice way to check if there is multiple `/r`

File: src/main/java/seedu/address/model/person/Phone.java [hunk 3]
```diff
@@ -11,8 +11,8 @@ public class Phone {
 
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Phone numbers should only contain numbers, and it should be at least 3 digits long";
-    public static final String VALIDATION_REGEX = "\\d{3,}";
+            "Phone numbers should only contain numbers, and it should exactly 8 digits long";
+    public static final String VALIDATION_REGEX = "\\d{8}";
```
Comment (brendanneojw) [inline src/main/java/seedu/address/model/person/Phone.java:15]: This only restricts it to singapore handphone numebrs, nice!

**Review by brendanneojw — COMMENTED** [review]
Overall, LGTM!
