### PR TITLE
Handle exceptional cases that might occur while using the add command

### LINKED ISSUE #63: Modify add command to handle all exceptions that could occur
As a beginner, I can add new car owners to my database, so that I can expand my client list.

### PR DESCRIPTION
**Pull request by RSXIX**
The program will specify which parameters are missing if an add command is incomplete.

The user is also now required to either include all or none of the policy variables when using the add command.

Closes #63

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 1]
```diff
@@ -45,10 +48,32 @@ public AddCommand parse(String args) throws ParseException {
...
+        }
+
         if (!arePrefixesPresent(argMultimap, PREFIX_NAME, PREFIX_PHONE, PREFIX_EMAIL, PREFIX_NRIC,
-                PREFIX_LICENCE_PLATE, PREFIX_ADDRESS)
-                || !argMultimap.getPreamble().isEmpty()) {
-            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, AddCommand.MESSAGE_USAGE));
+                PREFIX_LICENCE_PLATE, PREFIX_ADDRESS)) {
+            String errorMessage = MESSAGE_MISSING_FIELDS_FOR_ADD_COMMAND;
+            if (argMultimap.getValue(PREFIX_NAME).isEmpty()) {
+                errorMessage += "- Name(n/) ";
```
Comment (KumChaiYin) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: I think a good practice here should be using PREFIX_NAME instead of "n/" but current version won't cause any error. 
```suggestion
                errorMessage += "- Name("  + PREFIX_NAME + ") ";
```

File: src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java [hunk 2]
```diff
@@ -35,4 +35,5 @@ public void parse_emptyArg_throwsParseException() {
     public void parse_invalidArgs_throwsParseException() {
         assertParseFailure(parser, "a", String.format(Messages.MESSAGE_IMPOSSIBLE_INDEX, DeleteCommand.MESSAGE_USAGE));
     }
+
```
Comment (KumChaiYin) [inline src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java:38]: I think this might violate the checkStyle.

File: src/main/java/seedu/address/logic/Messages.java [hunk 3]
```diff
@@ -18,7 +18,17 @@ public class Messages {
 
     public static final String MESSAGE_IMPOSSIBLE_INDEX = "Error: The parameter is not of the type positive integer";
 
+    public static final String MESSAGE_PREAMBLE_DETECTED = "Error: Preamble Detected";
 
+    public static final String MESSAGE_MISSING_FIELDS_FOR_ADD_COMMAND =
+            "Error: Some of the required fields are missing. "
+            + "\n"
+            + "Please include the following: ";
```
Comment (KumChaiYin) [inline src/main/java/seedu/address/logic/Messages.java:26]: This message is useful to the users. Thank you for the initiative.

**Review by KumChaiYin — COMMENTED** [review]
just point out some minor error in coding practice.
Other looks good to me, doesn't have any logic error.

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java (hunk 1 above)
Comment (brendanneojw) [reply src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Yup agree with Chai Yin, since we already have the prefix declared we should use it rather than hard coding the string itself

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 4]
```diff
@@ -45,10 +48,32 @@ public AddCommand parse(String args) throws ParseException {
...
+            }
+            if (argMultimap.getValue(PREFIX_PHONE).isEmpty()) {
+                errorMessage += "- Phone(p/) ";
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Hence following Chai Yin suggestion, i will make the necessary changes here

```suggestion
                errorMessage += "- Phone(" + PREFIX_PHONE + ") ";
```

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 5]
```diff
@@ -45,10 +48,32 @@ public AddCommand parse(String args) throws ParseException {
...
+            }
+            if (argMultimap.getValue(PREFIX_EMAIL).isEmpty()) {
+                errorMessage += "- Email(e/) ";
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]:
```suggestion
                errorMessage += "- Email(" + PREFIX_EMAIL" + ") ";
```

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 6]
```diff
@@ -45,10 +48,32 @@ public AddCommand parse(String args) throws ParseException {
...
+            }
+            if (argMultimap.getValue(PREFIX_NRIC).isEmpty()) {
+                errorMessage += "- NRIC(i/) ";
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]:
```suggestion
                errorMessage += "- NRIC(+ " PREFIX_NRIC + ") ";
```

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 7]
```diff
@@ -45,10 +48,32 @@ public AddCommand parse(String args) throws ParseException {
...
+            }
+            if (argMultimap.getValue(PREFIX_LICENCE_PLATE).isEmpty()) {
+                errorMessage += "- License Plate(l/) ";
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]:
```suggestion
                errorMessage += "- License Plate(" + PREFIX_LICENCE_PLATE + ") ";
```

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 8]
```diff
@@ -45,10 +48,32 @@ public AddCommand parse(String args) throws ParseException {
...
+            }
+            if (argMultimap.getValue(PREFIX_ADDRESS).isEmpty()) {
+                errorMessage += "- Address(a/) ";
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]:
```suggestion
                errorMessage += "- Address(" + PREFIX_ADDRESS + ") ";
```

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 9]
```diff
@@ -61,7 +86,25 @@ public AddCommand parse(String args) throws ParseException {
...
         Set<Tag> tagList = ParserUtil.parseTags(argMultimap.getAllValues(PREFIX_TAG));
 
-        // temporary variables to change
+        if (!arePrefixesAbsent(argMultimap, PREFIX_POLICY_NUMBER, PREFIX_POLICY_ISSUE_DATE,
+                PREFIX_POLICY_EXPIRY_DATE)) {
+            if (!arePrefixesPresent(argMultimap, PREFIX_POLICY_NUMBER, PREFIX_POLICY_ISSUE_DATE,
+                    PREFIX_POLICY_EXPIRY_DATE)) {
+                String errorMessage = MESSAGE_MISSING_FIELDS_POLICY_FOR_ADD_COMMAND;
+                if (argMultimap.getValue(PREFIX_POLICY_NUMBER).isEmpty()) {
+                    errorMessage += "- Policy Number(pn/) ";
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]:
```suggestion
                    errorMessage += "- Policy Number(" + PREFIX_POLICY_NUMBER + ") ";
```

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 10]
```diff
@@ -61,7 +86,25 @@ public AddCommand parse(String args) throws ParseException {
...
+                }
+                if (argMultimap.getValue(PREFIX_POLICY_ISSUE_DATE).isEmpty()) {
+                    errorMessage += "- Policy Issue Date(pi/) ";
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]:
```suggestion
                    errorMessage += "- Policy Issue Date(" + PREFIX_POLICY_ISSUE_DATE + ") ";
```

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 11]
```diff
@@ -61,7 +86,25 @@ public AddCommand parse(String args) throws ParseException {
...
+                }
+                if (argMultimap.getValue(PREFIX_POLICY_EXPIRY_DATE).isEmpty()) {
+                    errorMessage += "- Policy Expiry Date(pe/) ";
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]:
```suggestion
                    errorMessage += "- Policy Expiry Date(" + PREFIX_POLICY_EXPIRY_DATE + ") ";
```

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 12]
```diff
@@ -45,10 +48,32 @@ public AddCommand parse(String args) throws ParseException {
...
+        }
+
         if (!arePrefixesPresent(argMultimap, PREFIX_NAME, PREFIX_PHONE, PREFIX_EMAIL, PREFIX_NRIC,
-                PREFIX_LICENCE_PLATE, PREFIX_ADDRESS)
-                || !argMultimap.getPreamble().isEmpty()) {
-            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, AddCommand.MESSAGE_USAGE));
+                PREFIX_LICENCE_PLATE, PREFIX_ADDRESS)) {
+            String errorMessage = MESSAGE_MISSING_FIELDS_FOR_ADD_COMMAND;
+            if (argMultimap.getValue(PREFIX_NAME).isEmpty()) {
+                errorMessage += "- Name("  + PREFIX_NAME + ") ";
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]:
```suggestion
                errorMessage += "- Name(" + PREFIX_NAME + ") ";
```

**Review by brendanneojw — COMMENTED** [review]
Overall LGTM! Have committed a small change by Chai Yin which I believe it will be beneficial in terms of code quality hence I've extend it to the other fields.

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 13]
```diff
@@ -45,10 +48,32 @@ public AddCommand parse(String args) throws ParseException {
...
+                PREFIX_LICENCE_PLATE, PREFIX_ADDRESS)) {
+            String errorMessage = MESSAGE_MISSING_FIELDS_FOR_ADD_COMMAND;
+            if (argMultimap.getValue(PREFIX_NAME).isEmpty()) {
+                errorMessage += "- Name(" + PREFIX_NAME + ") ";
+            }
+            if (argMultimap.getValue(PREFIX_PHONE).isEmpty()) {
+                errorMessage += "- Phone(" + PREFIX_PHONE + ") ";
+            }
+            if (argMultimap.getValue(PREFIX_EMAIL).isEmpty()) {
+                errorMessage += "- Email(" + PREFIX_EMAIL" + ") ";
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]:
```suggestion
                errorMessage += "- Email(" + PREFIX_EMAIL + ") ";
```

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 14]
```diff
@@ -45,10 +48,32 @@ public AddCommand parse(String args) throws ParseException {
...
+                errorMessage += "- Name(" + PREFIX_NAME + ") ";
+            }
+            if (argMultimap.getValue(PREFIX_PHONE).isEmpty()) {
+                errorMessage += "- Phone(" + PREFIX_PHONE + ") ";
+            }
+            if (argMultimap.getValue(PREFIX_EMAIL).isEmpty()) {
+                errorMessage += "- Email(" + PREFIX_EMAIL + ") ";
+            }
+            if (argMultimap.getValue(PREFIX_NRIC).isEmpty()) {
+                errorMessage += "- NRIC(+ " PREFIX_NRIC + ") ";
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]:
```suggestion
                errorMessage += "- NRIC(" + PREFIX_NRIC + ") ";
```

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 15]
```diff
@@ -45,10 +48,32 @@ public AddCommand parse(String args) throws ParseException {
...
+            if (argMultimap.getValue(PREFIX_NRIC).isEmpty()) {
+                errorMessage += "- NRIC(" + PREFIX_NRIC + ") ";
+            }
+            if (argMultimap.getValue(PREFIX_LICENCE_PLATE).isEmpty()) {
+                errorMessage += "- License Plate(" + PREFIX_LICENCE_PLATE + ") ";
+            }
+            if (argMultimap.getValue(PREFIX_ADDRESS).isEmpty()) {
+                errorMessage += "- Address(" + PREFIX_ADDRESS + ") ";
+            }
+            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, errorMessage));
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java:76]: Nice way to show the user if any of the fields are missing, it will directly show which are the ones that are missing

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 16]
```diff
@@ -61,7 +86,25 @@ public AddCommand parse(String args) throws ParseException {
...
+                String errorMessage = MESSAGE_MISSING_FIELDS_POLICY_FOR_ADD_COMMAND;
+                if (argMultimap.getValue(PREFIX_POLICY_NUMBER).isEmpty()) {
+                    errorMessage += "- Policy Number(" + PREFIX_POLICY_NUMBER + ") ";
+                }
+                if (argMultimap.getValue(PREFIX_POLICY_ISSUE_DATE).isEmpty()) {
+                    errorMessage += "- Policy Issue Date(" + PREFIX_POLICY_ISSUE_DATE + ") ";
+                }
+                if (argMultimap.getValue(PREFIX_POLICY_EXPIRY_DATE).isEmpty()) {
+                    errorMessage += "- Policy Expiry Date(" + PREFIX_POLICY_EXPIRY_DATE + ") ";
+                }
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java:102]: Same goes for here, very nicely done
