### PR TITLE
Handle exceptions in find command

### LINKED ISSUE #66: Modify find command to handle all kinds of exceptions that could occur
As a beginner user I can search for a specific car owner by their profile details, so that I can quickly access their information.

The application should give me an error for the following exceptions:
1. Format error in any field: `Error: Please adhere to the format for the fields`
2. No field given: `Error: Please give at least one field`
3. Field flag given but no value: `Error: Please give a value in the field(s) indicated`

Naming of the output are just examples

### PR DESCRIPTION
**Pull request by cyaoxuan**
Closes #66 

- Updated UG to reflect expected output

Additional exceptions handled:
- No fields given (e.g. `find`, `find a`)
- Empty fields

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java [hunk 1]
```diff
@@ -64,35 +66,87 @@ public FindCommand parse(String args) throws ParseException {
...
         }
         if (argMultimap.getValue(PREFIX_COMPANY).isPresent()) {
             companyKeyword = argMultimap.getValue(PREFIX_COMPANY).get();
+            if (companyKeyword.isEmpty()) {
+                emptyPrefixes += PREFIX_COMPANY + " ";
+            }
+            atLeastOneFieldPresent = true;
+        }
+
+        if (!atLeastOneFieldPresent) {
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/parser/FindCommandParser.java:143]: Seems like this is to check if at least 1 field is present, as shown in the UG. Nice!

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java [hunk 2]
```diff
@@ -64,35 +66,87 @@ public FindCommand parse(String args) throws ParseException {
...
+            throw new ParseException(
+                    String.format(MESSAGE_INVALID_COMMAND_FORMAT, FindCommand.MESSAGE_USAGE));
+        }
+
+        if (!emptyPrefixes.isEmpty()) {
```
Comment (brendanneojw) [inline src/main/java/seedu/address/logic/parser/FindCommandParser.java:148]: This looks like handling the error if a user specify a prefix, but no values. Nicely done!

**Review by brendanneojw — COMMENTED** [review]
LGTM!
